### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by daukadolt** [stgmadina/madina.github.io#1]
В index.html вы забыли добавить

`
публичная статичная пустая функция Главная(Массив аргументы) {
}
`

**Comment by stgmadina** [comment]
i 4e

**Comment by daukadolt** [comment]
Не дид мыңау

**Comment by stgmadina** [comment]
i 4e dim

**Comment by daukadolt** [comment]
қызықсың сен братишка

**Comment by stgmadina** [comment]
otdyhai

**Comment by daukadolt** [comment]
е, қай жердікі боласың өзің?

**Comment by stgmadina** [comment]
Taraz

**Comment by daukadolt** [comment]
уважительно сөйлесетін шығарсың бәлкім?

**Comment by stgmadina** [comment]
negldinsn

**Comment by daukadolt** [comment]
The issue has been resolved

**Comment by stgmadina** [comment]
@daukadolt Spi
